#!/bin/sh

# Mount required directories. Due to wanting mdev support on a read-only
# filesystem, /dev is mounted as a tmpfs filesystem.
# Note that /dev contains null and console in order for kernel to boot at all!
mount -n -t proc /proc /proc
mount -n -t sysfs sysfs /sys
mount -n -t tmpfs mdev /dev

# All media will be mounted from /mnt, which is symlink to /var/tmpfs/mnt
# /var/tmpfs is symlink to /tmp
mount -n -t tmpfs tmpfs /tmp
mkdir /mnt/internal

# Seed /dev with some things that we know we need (from busybox-init scripts)

# Not provided by sysfs but needed
ln -snf /proc/self/fd /dev/fd
ln -snf fd/0 /dev/stdin
ln -snf fd/1 /dev/stdout
ln -snf fd/2 /dev/stderr
[ -e /proc/kcore ] && ln -snf /proc/kcore /dev/core

mkdir /dev/pts /dev/shm

# Set up mdev to handle hotplug events
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
mdev -s

#Now mount anything in left fstab
mount -a

#Set hostname
/bin/hostname -F /etc/hostname

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

