#
# Makefile for misc devices that really don't fit anywhere else.
#
obj- := misc.o	# Dummy rule to force built-in.o to be made

obj-$(CONFIG_IBM_ASM)	+= ibmasm/
obj-$(CONFIG_HDPU_FEATURES)	+= hdpuftrs/
obj-$(CONFIG_NEUROS_GENERIC) += neuros_generic.o
obj-$(CONFIG_NEUROS_IR_BLASTER) += neuros_ir_blaster.o
obj-$(CONFIG_XLOCK) += xlock.o
