zreladdr-$(CONFIG_ARCH_ITDM320_20)     := $(CONFIG_KERNEL_LOAD_ADDR)
params_phys-$(CONFIG_ARCH_ITDM320_20)   := $(CONFIG_KERNEL_PARAM_ADDR)
initrd_phys-$(CONFIG_ARCH_ITDM320_20)   := $(CONFIG_KERNEL_INITRD_ADDR)
