# $Id: Makefile,v 1.1.1.1 2006/01/06 00:51:14 jsantiago Exp $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

obj-y := init.o console.o printf.o  misc.o
#bootstr.o init.o misc.o segment.o console.o printf.o
